name: Build and Push (release)

on:
  # Trigger the workflow on all tagged pushes, but not for newly created branches  
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Branch info
        id: branch_info
        run: | 
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: eduardrosert/python-k8s-controller:latest,eduardrosert/python-k8s-controller:${{ steps.branch_info.outputs.SOURCE_TAG }}